CREATE TABLE IF NOT EXISTS "sc-acervo-digital".media_item (
  id UUID PRIMARY KEY,
  media_public_key VARCHAR(80) NOT NULL UNIQUE,
  entity_type VARCHAR(40) NOT NULL,
  entity_id UUID NOT NULL,
  owner_public_key VARCHAR(80),
  boat_public_key VARCHAR(80),
  accommodation_code VARCHAR(120),
  media_type VARCHAR(20) NOT NULL,
  purpose VARCHAR(30) NOT NULL,
  visibility VARCHAR(20) NOT NULL,
  status VARCHAR(30) NOT NULL,
  title VARCHAR(255),
  description TEXT,
  is_main BOOLEAN NOT NULL DEFAULT FALSE,
  display_order INTEGER,
  rejection_reason_code VARCHAR(120),
  rejection_reason_description TEXT,
  object_path TEXT NOT NULL,
  mime_type VARCHAR(150) NOT NULL,
  size_bytes BIGINT NOT NULL,
  cdn_url TEXT,
  source_type VARCHAR(60),
  responsible_declaration BOOLEAN,
  has_image_use_authorization BOOLEAN,
  allows_commercial_use BOOLEAN,
  allows_marketing_use BOOLEAN,
  allows_social_media_use BOOLEAN,
  approved_at TIMESTAMP,
  published_at TIMESTAMP,
  created_at TIMESTAMP NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMP NOT NULL DEFAULT NOW()
);
